-- MySQL Script generated by MySQL Workbench
-- Mon Apr 17 21:00:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Receita
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Receita
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Receita` DEFAULT CHARACTER SET utf8 ;
USE `Receita` ;

-- -----------------------------------------------------
-- Table `Receita`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Receita`.`usuario` (
  `id_usuario` VARCHAR(16) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`));


-- -----------------------------------------------------
-- Table `Receita`.`Receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Receita`.`Receita` (
  `nome_receita` INT NOT NULL AUTO_INCREMENT,
  `ingredientes` TEXT NOT NULL,
  `modopreparo` TEXT NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`nome_receita`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
